### ISSUE TITLE
jssip / phonertc version compatibility?

### ISSUE THREAD

**Issue by massaroni** [versatica/jssip-cordova#1]
Which versions of [jssip](https://github.com/versatica/JsSIP) does the latest jssip-cordova support?  I'm testing jssip-cordova 0.1.2 with jssip 0.6.2, and the code sample in the jssip-cordova readme doesn't seem to be working, and it's probably intended for a different version of jssip because the 0.6.2 codebase doesn't contain the string rtcEngine anywhere.

[phonertc](https://github.com/alongubkin/phonertc) doesn't have version numbers yet, but I would ask about compatibility with that plugin as well.

**Comment by ibc** [comment]
This project will be deleted soon. Being based on PhoneRTC is a pain (under my experience). PhoneRTC crashes if the "video container" does not exist before making the call or if it is not a pure square, or even if its size is calculated dynamically via CSS3 FlexBox, etc). Even worse, PhoneRTC mandates a signaling protocol which makes it very hard to work with SIP (and hence the whole hack/workaround or jssip-cordova).

The way to go is Cordova + new versions of Android WebView, which natively support WebRTC. That would fail in iOS of course.

Said that, no one official version of JsSIP has been compatible with jssip-cordova, but just this commit: 0acf0f8700b80168c5ea29f7cbe7aeb5731e9b68

**Comment by massaroni** [comment]
Thanks for the quick reply, ibc.  Are there any other iOS Cordova RTC plugins out there you would recommend?

**Comment by ibc** [comment]
No, but I already said: use the latest Android WebView (Chrome Engine) which does support WebRTC: https://crosswalk-project.org/

**Comment by massaroni** [comment]
Sounds good, thanks for the help.
